title: Kangmin's blog
email: codemin1005@gmail.com
author: Kangmin Moon

home:
  heading: "Affectionately"
  subheading: "Algorithm,AI,Web,App,Compiler,DataScience"
  banner: "Your image url"

description: hi
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

click_to_top:
  light:
    background_color: "white"
    color: "#454545"
  dark:
    background_color: "#34323d"
    color: "#bbb"

# Gitment comments
gitment:
  username: "Your GitHub username"
  repo: "The repo to store comments"
  client_id: "Your client ID"
  client_secret: "Your client secret"
  redirect_uri: "Your redirect url"   # If you use a custom domain name

# Build settings
remote_theme: "jeffreytse/jekyll-theme-yat"
plugins:
  - jekyll-theme-yat
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

markdown: kramdown
kramdown:
  input: GFM

future: true
