name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master  # 또는 master 브랜치

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.4'  # 사용하고 있는 Ruby 버전

    - name: Install dependencies
      env:
        GEM_HOME: ${{ github.workspace }}/vendor/bundle
        GEM_PATH: ${{ github.workspace }}/vendor/bundle
      run: |
        gem install bundler
        bundle install --path vendor/bundle

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages


